version: 0.2

phases:
  build:
    commands:
      - docker login -u philip.nilsson -p yacloud1 https://git.systementor.se
      - docker build -f Dockerfile -t git.systementor.se/philip.nilsson/yacloudreact .
      - docker push git.systementor.se/philip.nilsson/yacloudreact